spring:
     jpa:
        hibernate:
             ddl-auto: none

  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
# spring:
  h2:
    console:
      enabled: true
      path: /console

